# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version = 1.21.11
loader_version = 0.18.4
loom_version = 1.15-SNAPSHOT

# Mod Properties
mod_name = Tooltips
mod_version = 1.0.0
mod_author = Nitroito
mod_description = A Fabric mod with a new fresh look for your tooltips.
maven_group = pt.nitroito.tooltips

# Dependencies
fabric_api = 0.140.2+1.21.11
mod_menu = 17.0.0
cloth_config = 21.11.153