# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version = 26.2
loader_version = 0.19.3
loom_version = 1.17-SNAPSHOT

# Mod Properties
mod_name=Tooltips
mod_version=1.2.0
mod_author=Nitroito
mod_description=A Fabric mod with a new fresh look for your tooltips.
maven_group=pt.nitroito.tooltips

# Dependencies
fabric_api = 0.153.0+26.2
mod_menu = 20.0.0-beta.4
cloth_config = 26.2.155
